#!/bin/bash
set -e
VERSION=0.2

if [ "$1" = "--help" ]; then
    echo "Dockerize Version $VERSION"
    echo "See https://github.com/stefanklug/dockerize"
    echo "Usage: $0 [command]"
    exit 0
fi


DOCKERIZE_DIR=$(pwd)

while [ ! -f ".dockerize" -a $(pwd) != "/" ]; do
    cd ..
done

if [ ! -f ".dockerize" ]; then
    echo "No .dockerize file found in the current directory or any parent directories."
    exit 1
fi

source .dockerize

TAGNAME=dockerize

USERID=$(id -u)
GROUPID=$(id -g)

if [ -n "$DOCKERFILE" -a -n "$DOCKERIMAGE" ]; then
    echo "Please specify either DOCKERIMAGE or DOCKERFILE, but not both"
    exit 1
fi

if [ -z "$DOCKERFILE" -a -z "$DOCKERIMAGE" ]; then
    echo "Please specify either DOCKERIMAGE or DOCKERFILE"
    exit 1
fi

if [ -n "$DOCKERIMAGE" ]; then
    PATCHED_DOCKERFILE=$(mktemp "$(pwd)/Dockerfile.dockerizeXXXXXXX")
    echo "FROM $DOCKERIMAGE" >> $PATCHED_DOCKERFILE
elif [ -n "$DOCKERFILE" ]; then
    if [ ! -f "$DOCKERFILE" ]; then
        echo "Dockerfile '$DOCKERFILE' does not exist."
        exit 1
    fi
    # create a temporary dockerfile
    f=$(realpath "$DOCKERFILE")
    PATCHED_DOCKERFILE=$(mktemp "$f.dockerizeXXXXXXX")
    cat $f > $PATCHED_DOCKERFILE
else
    echo "Please specify either DOCKERIMAGE or DOCKERFILE"
    exit 1
fi

if [ -n "$DOCKERFILE_APPEND" ]; then
    echo "$DOCKERFILE_APPEND" >> $PATCHED_DOCKERFILE
fi


entrypoint_base64=$(base64 -w0 - << 'EOF'
#!/bin/sh
# This entrypoint
# - creates a user and group for the current uid/gid, if they don't exist.
# - jumps to DOCKERIZE_DIR
# - execs $@

if ! which sudo > /dev/null; then
    echo "sudo is missing in the image"
    exit 1
fi

# Ensure we can sudo, which might be problematic in qemu environments
if sudo true 2>&1 | grep "effective uid is not 0"; then
    echo "sudo is not working properly. If this is running using binfmt extensions"
    echo "and qemu, the registration might be insufficient. To solve this one can"
    echo "register binfmt extensions with extended permissions."
    echo "ATTENTION: This might be a security risk, so handle with care:"
    echo "docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes --credential yes"
    exit 1
fi

if ! getent group $(id -g) > /dev/null; then
    /usr/sbin/groupadd -g $(id -g) group$(id -g)
else
    echo "Group with id $(id -g) exists."
fi

if ! getent passwd $(id -u) > /dev/null; then
    /usr/sbin/useradd -u $(id -u) -g $(id -g) -d $HOME user$(id -u)
    sudo chown $(id -u):$(id -g) $HOME
else
    echo "ERROR: User with id $(id -u) exists. This causes all kinds of issues.\n"
    echo "The easiest way to solve this is to add the following line to .dockerize:\n"
    echo "DOCKERFILE_APPEND=\"\"\""
    echo "  RUN userdel -r \\\$(getent passwd $(id -u) | cut -f 1 -d ':')\""
    echo "\"\"\""
    exit 1
fi

sudo chmod a-s /usr/sbin/useradd && sudo chmod a-s /usr/sbin/groupadd

echo "You got dockerized!"

cd $DOCKERIZE_DIR
unset DOCKERIZE_DIR
exec "$@"
EOF
)

cat << EOF >> "$PATCHED_DOCKERFILE"

# prepare for dockerize
RUN echo "$entrypoint_base64" | base64 -d - > /bin/entrypoint.sh && chmod +x /bin/entrypoint.sh
RUN echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
# allow useradd and groupadd to be called from entrypoint without sudo
# as the user that would do sudo doesn't exist, yet
RUN chmod a+s /usr/sbin/useradd && chmod a+s /usr/sbin/groupadd

# Create the home directory for the user, so that we can later chown it in cases
# where the dockerized directory is a subdirectory of the home dir.
RUN mkdir $HOME
ENTRYPOINT [ "/bin/entrypoint.sh" ]
EOF

# Don't exit on error so we can remove the dockerfile
set +e

# if an image is used, build should be done without context
if [ -n "$DOCKERIMAGE" ]; then
    docker build -t $TAGNAME - < $PATCHED_DOCKERFILE
else
    docker build -f $PATCHED_DOCKERFILE -t $TAGNAME .
fi

ret=$?

# restore exit on error
set -e

rm $PATCHED_DOCKERFILE

if [ $ret -ne 0 ]; then
    echo "Docker build failed"
    exit $ret
fi


ARGS=""
if [ "$DOCKERIZE_MOUNT_HOME" = "1" ]; then
 ARGS="$ARGS -v $HOME:$HOME"
fi

ARGS="$ARGS -e HOME=$HOME"

if [ -n "$DOCKERIZE_ARGS" ]; then
 ARGS="$ARGS $DOCKERIZE_ARGS"
fi

docker run --rm -ti -u $USERID:$GROUPID $ARGS -v $(pwd):$(pwd) -e DOCKERIZE_DIR=$DOCKERIZE_DIR $TAGNAME /bin/bash
